### ISSUE TITLE
素材管理文档有一处错误

### ISSUE THREAD

**Issue by Gaoxin1996** [EasyWeChat/docs#110]
URL:https://www.easywechat.com/docs/master/zh-CN/official-account/material
获取永久素材列表处示例代码为:$app->material->list($type, $offset, $count);
实际上应为:$app->material->lists($type, $offset, $count);

**Comment by overtrue** [comment]
没有错误：

https://github.com/overtrue/wechat/blob/master/src/OfficialAccount/Material/Client.php#L204
