### ISSUE TITLE
找不到jssdk的普通文档

### ISSUE THREAD

**Issue by wang199296** [EasyWeChat/docs#140]
以前3.1版本使用jssdk是可以使用的，现在不行了，  找文档直接跳到企业的jssdk里面了

**Comment by overtrue** [comment]
3.x: https://www.easywechat.com/docs/3.x/zh-CN/js
4.0: https://www.easywechat.com/docs/master/zh-CN/basic-services/jssdk

**Comment by overtrue** [comment]
因为企业微信的 jssdk 用法是一样的

**Comment by overtrue** [comment]
企业微信与公众号的 jssdk 是一样的 https://work.weixin.qq.com/api/doc#10029
