### ISSUE TITLE
网页授权那里有问题

### ISSUE THREAD

**Issue by cuiziwei** [EasyWeChat/docs#167]
https://www.easywechat.com/docs/master/zh-CN/official-account/oauth

如果在 oauth callback 之前写入 $_SESSION['target_url'] ，之后微信回调后到 user/profile 页面是获取不到这个 target_url 的，是因为微信回调的没有携带 cookie？所以导致获取不到对应的 session id，我是在 laravel 试的获取不到。用的别的方法：配置 callback url 时候多加了一个 target_url 的参数。

**Comment by overtrue** [comment]
“微信回调的没有携带 cookie” 只要在浏览器里就肯定有，除非你修改过浏览器。
