### ISSUE TITLE
文档几个超链接有点问题。

### ISSUE THREAD

**Issue by phz** [EasyWeChat/docs#33]
几处docs不该存在。

contributing.md:
   54: 当你在使用过程中遇到问题，请查阅  疑难解答 (http://easywechat.org/ `docs/`troubleshooting.html) 

events.md:
   40: 更多请参考： 服务端(`docs/`server.html)

index.md:
已经做了汇总：  疑难解答(`docs/`troubleshooting.html) ，如果你在问题疑难解

messages.md:
  335: 请参考： 群发消息(`docs/`broadcast.html)

server.md:
  154: 关于消息的使用，请参考 消息(`docs/`messages.html) 章节。

**Comment by overtrue** [comment]
@phz 感谢！已经修复 ❤️
