### ISSUE TITLE
想咨询一下该文档的html格式是什么工具生成的

### ISSUE THREAD

**Issue by anyforever** [EasyWeChat/docs#52]
想咨询一下该文档的html格式是什么工具生成的，可以吗？

**Comment by overtrue** [comment]
https://laravel-china.org/topics/1965

**Comment by anyforever** [comment]
@overtrue 好的，收到。太感谢了。

**Comment by tyaqing** [comment]
@overtrue 请问下贵站的论坛是自己做的还是基于开源产品呢

**Comment by overtrue** [comment]
https://github.com/flarum/flarum

发自我的 iPhone
