### ISSUE TITLE
 docs/zh-CN/official-account/template_message.md

### ISSUE THREAD

**Issue by birdol** [EasyWeChat/docs#99]
$app->template_message->send([
        'touser' => 'user-openid',
        'template_id' => 'template-id',
        'url' => 'https://easywechat.org',
        'title' => 'title',
        'data' => [
            'key1' => 'VALUE',
            'key2' => 'VALUE2',
            ...
        ],
    ]);

其中的title是干啥的？   微信官方的文档里没看到这个参数，sdk里好像也没有使用？

**Comment by overtrue** [comment]
遗留的吧，最开始有的
